default_language_version:
  python: python3.10.5
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
- repo: https://github.com/python-poetry/poetry
  rev: 1.2.0rc2
  hooks:
  # - id: poetry-check # Takes too long (~5 min)
  - id: poetry-lock
