name: cd
on:
  push:
    branches: [master]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup machine
      uses: ./.github/actions/setup

    - name: Build package
      run: |
        poetry build

    - name: Publish
      # Should come from the repo configuration as secrets
      if: ${{ secrets.REPO_USERNAME != null }} && ${{ secrets.REPO_PASSWORD != null }}
      run: |
        poetry config repositories.company-internal https://repo.company.com/repository/pypi-internal
        poetry config http-basic.company-internal $REPO_USERNAME $REPO_PASSWORD

        poetry publish -r company-internal
